#!/usr/bin/env python

import httplib, urllib, sys

def compile(code):
    """
    Sends the JavaScript to the Google Closure compiler and returns
    the transformed output.
    """
    # Define the parameters for the POST request and encode them in
    # a URL-safe format.
    params = urllib.urlencode([
        ('js_code', code),
        ('compilation_level', 'SIMPLE_OPTIMIZATIONS'),
        ('output_format', 'text'),
        ('output_info', 'compiled_code'),
      ])

    # Always use the following value for the Content-type header.
    headers = { "Content-type": "application/x-www-form-urlencoded" }
    conn = httplib.HTTPConnection('closure-compiler.appspot.com')
    conn.request('POST', '/compile', params, headers)
    response = conn.getresponse()
    data = response.read()
    conn.close()
    return data


def main():
    source = ""
    sourcePath = './src/cobra.js'
    file = open(sourcePath, 'r')
    source += file.read()
    file.close()

    output = open('cobra.min.js', 'w')
    output.write(compile(source))
    output.close()

if __name__ == '__main__':
    main()
